apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: container-myapp
        image: ayswarya430/app:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: myapp